### ISSUE TITLE
New future request 

### ISSUE THREAD

**Issue by dqanshi** [cachecleanerjeet/WhatsBot#54]
Please add spam and bombs msgs

**Comment by cyberboysumanjay** [comment]
https://www.hindustantimes.com/india-news/banned-over-2-million-indian-accounts-in-august-says-whatsapp-101633153579946-amp.html

![Screenshot_20211003-125125049 (1)](https://user-images.githubusercontent.com/12748990/135744241-b58e0912-4ba9-446d-a358-5deb6b0bd06c.jpg)

**Comment by cachecleanerjeet** [comment]
Yes, exactly !
